#ifndef WEATHER_IDS_H
#define WEATHER_IDS_H

#define WEATHER_NONE 0x0
#define WEATHER_SUNNY 0x1
#define WEATHER_RAIN 0x2
#define WEATHER_SANDSTORM 0x3
#define WEATHER_HAIL 0x4
#define WEATHER_SHADOWY_AURA 0x5
#define WEATHER_FOG 0x6
#define WEATHER_HARSH_SUNLIGHT 0x7
#define WEATHER_HEAVY_RAIN 0x8
#define WEATHER_MYSTERIOUS_AIR_CURRENT 0x9


#endif /* WEATHER_IDS_H */
